using System.IO;

namespace test
{
    /// <summary>
    /// Reads in a stream generated by Recorder and saves the first depth frame as
    /// a .pgm file to verify that the recording function works correctly.
    /// </summary>
    class RecorderTest
    {
        public static void Depth2PGM(string src, string dst)
        {
            byte[] frame = new byte[640*480*2];

            // Read .depth
            FileStream fs_src = File.Open(src, FileMode.Open);
            BinaryReader br = new BinaryReader(fs_src);

            br.BaseStream.Seek(71, SeekOrigin.Begin);   // skip to first depth frame
            br.Read(frame, 0, 640 * 480 * 2);

            br.Close();
            fs_src.Close();

            // Write .pgm
            FileStream fs_dst = File.Open(dst, FileMode.Create);
            BinaryWriter bw = new BinaryWriter(fs_dst);

            bw.Write("P5 640 480 65535\n".ToCharArray());
            bw.Write(frame);

            bw.Close();
            fs_dst.Close();

        }
    }
}
